export const hardExcursiones = [
  {
    name: "Rio manso",
    primaryImage: "imagen primaria",
    secondaryImage: "imagen secundaria",
    description: "raft por el rio",
    location: "Bariloche",
    date: "12/03/2022",
    time: "13.30",
    price: 2500.00,
    extra: "extra",
  },
  {
    name: "Cerro",
    primaryImage: "imagen primaria",
    secondaryImage: "imagen secundaria",
    description: "raft por el rio",
    location: "Bariloche",
    date: "12/03/2022",
    time: "13.30",
    price: 2500.00,
    extra: "extra",
  },
  {
    name: "Rio manso",
    primaryImage: "imagen primaria",
    secondaryImage: "imagen secundaria",
    description: "raft por el rio",
    location: "Bariloche",
    date: "12/03/2022",
    time: "13.30",
    price: 2500.00,
    extra: "extra",
  },
  {
    name: "Rio manso",
    primaryImage: "imagen primaria",
    secondaryImage: "imagen secundaria",
    description: "raft por el rio",
    location: "Bariloche",
    date: "12/03/2022",
    time: "13.30",
    price: 2500.00,
    extra: "extra",
  },
  {
    name: "Rio manso",
    primaryImage: "imagen primaria",
    secondaryImage: "imagen secundaria",
    description: "raft por el rio",
    location: "Bariloche",
    date: "12/03/2022",
    time: "13.30",
    price: 2500.00,
    extra: "extra",
  },
]